### ISSUE TITLE
Is there any essential difference between  "ff2n" and "fracfact"?

### ISSUE THREAD

**Issue by CodeEremite** [tisimst/pyDOE#15]
Excuse me.

As I know, full-factorial design can manipulate all the main and interaction effects already. The meaning of fraction factorial design is to reduce the runs based on that some interaction have little effect, such as some high-order interactions.

Why do I need "fracfact" if the runs of "fracfact" is equal or even bigger than the runs of "ff2n"? 
Just because "fracfact" can list the columns of interaction?

**Comment by tisimst** [comment]
@CodeEremite, since you closed the issue, would you mind commenting on why?

**Comment by tisimst** [comment]
@CodeEremite, since you closed the issue, would you mind commenting on why?
